export const CHECKOUT_ADDRESS_START = 'CHECKOUT_ADDRESS_START'
export const CHECKOUT_ADDRESS_FINISHED = 'CHECKOUT_ADDRESS_FINISHED'

export const CHECKOUT_PAYMENT_START = 'CHECKOUT_PAYMENT_START'
export const CHECKOUT_PAYMENT_FINISHED = 'CHECKOUT_PAYMENT_FINISHED'

export const CHECKOUT_CONFIRMED_START = 'CHECKOUT_CONFIRMED_START'
export const CHECKOUT_CONFIRMED_FINISHED = 'CHECKOUT_CONFIRMED_FINISHED'

export const CHECKOUT_STARTED = 'CHECKOUT_STARTED'
export const CHECKOUT_FINISHED = 'CHECKOUT_FINISHED'


