//auth user types AUTH_LOGOUT
export const AUTH_USER = 'AUTH_USER';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const AUTH_USER_LEFT = 'AUTH_USER_LEFT';
export const UPDATE_USER_LEFT = 'UPDATE_USER_LEFT';
export const CHECKOUT_LINK_ADD = 'CHECKOUT_LINK_ADD';
export const CHECKOUT_LINK_REMOVE = 'CHECKOUT_LINK_REMOVE';

//hintBox 
export const SHOW_HINTBOX = 'SHOW_HINTBOX';
export const HIDE_HINTBOX = 'HIDE_HINTBOX';
//favorite and seen
export const FRTCH_FAVORITES_START = 'FRTCH_FAVORITES_START';
export const FRTCH_FAVORITES_SUCCESS = 'FRTCH_FAVORITES_SUCCESS';
export const FRTCH_FAVORITES_ERROR = 'FRTCH_FAVORITES_ERROR';
export const FRTCH_SEEN_START = 'FRTCH_SEEN_START';
export const FRTCH_SEEN_SUCCESS = 'FRTCH_SEEN_SUCCESS';
export const FRTCH_SEEN_ERROR = 'FRTCH_SEEN_ERROR';
export const FAVORITE_LIST_ACTION = 'FAVORITE_LIST_ACTION';
export const SEEN_LIST_ACTION = 'SEEN_LIST_ACTION';



export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
export const AUTH_LINK_FACEBOOK = 'AUTH_LINK_FACEBOOK';
export const AUTH_LINK_GOOGLE = 'AUTH_LINK_GOOGLE';
export const AUTH_UNLINK_FACEBOOK = 'AUTH_UNLINK_FACEBOOK';
export const AUTH_UNLINK_GOOGLE = 'AUTH_UNLINK_GOOGLE';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const AUTH_ERROR = 'AUTH_ERROR';
export const DASHBOARD_DATA = 'DASHBOARD_DATA';

export const SET_DEFAULT_ADDRESS = 'SET_DEFAULT_ADDRESS';
export const FETCH_ADDRESSES = 'FETCH_ADDRESSES';
export const ADD_NEW_ADDRESS = 'ADD_NEW_ADDRESS';

export const MAKE_ORDER = 'MAKE_ORDER';
export const FETCH_ORDERS = 'FETCH_ORDERS';



//admin 
export const ADMIN_SIGN_UP = 'ADMIN_SIGN_UP';
export const ADMIN_SIGN_IN = 'ADMIN_SIGN_IN';
export const ADMIN_SIGN_OUT = 'ADMIN_SIGN_OUT';
export const ADMIN_AUTH_ERROR = 'ADMIN_AUTH_ERROR';
export const DASHBOARD_GET_DATA = 'DASHBOARD_GET_DATA';
export const  FETCH_ORDERS_ADMIN = 'FETCH_ORDERS_ADMIN'
export const  FETCH_ORDERS_ERRROR = 'FETCH_ORDERS_ERRROR'

//products
export const  FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const  FETCH_CATEGORY = 'FETCH_CATEGORY'
export const  FETCH_SECTIONS = 'FETCH_SECTIONS'
export const  FETCH_SECTIONS_WITH_PRODUCTS = 'FETCH_SECTIONS_WITH_PRODUCTS'
export const  FETCH_COLLECTIONS = 'FETCH_COLLECTIONS'
export const  PRODUCTS_IS_FETCHING = 'PRODUCTS_IS_FETCHING'
export const  SECTIONS_IS_FETCHING = 'SECTIONS_IS_FETCHING'
export const  CATEGORIES_IS_FETCHING = 'CATEGORIES_IS_FETCHING'
export const  COLLECTIONS_IS_FETCHING = 'COLLECTIONS_IS_FETCHING'
export const  PRODUCT_FETCHED = 'PRODUCT_FETCHED'


export const  ADDING_PRODUCT = 'ADDING_PRODUCT'
export const  ADDING_SECTION = 'ADDING_SECTION'
export const  ADDING_CATEGORY = 'ADDING_CATEGORY'
export const  ADDING_COLLECTION = 'ADDING_COLLECTION'

export const  FETCH_ERROR = 'FETCH_ERROR'

export const  FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR'
export const  FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'
export const  FETCH_SECTIONS_ERROR = 'FETCH_PRODUCTS_ERROR'
export const  FETCH_COLLECTIONS_ERROR = 'FETCH_COLLECTIONS_ERROR'

export const ADDED_TO_SERVER = 'ADDED_TO_SERVER'
export const ADDED_TO_SERVER_ERROR = 'ADDED_TO_SERVER_ERROR'



//cart
export const TOGGLE_CART = 'TOGGLE_CART'
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR'
export const CHECKOUT_FINISHED = 'CHECKOUT_FINISHED'

//ckeckout
export const CHECKOUT_ADDRESS_START = 'CHECKOUT_ADDRESS_START'
export const CHECKOUT_ADDRESS_FINISHED = 'CHECKOUT_ADDRESS_FINISHED'

export const CHECKOUT_PAYMENT_START = 'CHECKOUT_PAYMENT_START'
export const CHECKOUT_PAYMENT_FINISHED = 'CHECKOUT_PAYMENT_FINISHED'

export const CHECKOUT_CONFIRMED_START = 'CHECKOUT_CONFIRMED_START'
export const CHECKOUT_CONFIRMED_FINISHED = 'CHECKOUT_CONFIRMED_FINISHED'

export const CHECKOUT_STARTED = 'CHECKOUT_STARTED'



//langs

export const SET_ARABIC = 'SET_ARABIC'
export const SET_ENGLISH = 'SET_ENGLISH' 
export const SET_ARABIC_BROWSER = 'SET_ARABIC_BROWSER'
export const SET_ENGLISH_BROWSER = 'SET_ENGLISH_BROWSER' 
