export const  FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const  FETCH_CATEGORY = 'FETCH_CATEGORY'
export const  FETCH_SECTIONS = 'FETCH_SECTIONS'
export const  FETCH_COLLECTIONS = 'FETCH_COLLECTIONS'
export const  FETCH_ERROR = 'FETCH_ERROR'

export const  FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR'
export const  FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'
export const  FETCH_SECTIONS_ERROR = 'FETCH_PRODUCTS_ERROR'
export const  FETCH_COLLECTIONS_ERROR = 'FETCH_COLLECTIONS_ERROR'

export const ADDED_TO_SERVER = 'ADDED_TO_SERVER'
export const ADDED_TO_SERVER_ERROR = 'ADDED_TO_SERVER_ERROR'

