export const  FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const  FETCH_CATEGORY = 'FETCH_CATEGORY'
export const  FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR'
export const  FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'
